<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1c3c2c9db23e0de9bb6e5f83eda4c7b2
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Login\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Login\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1c3c2c9db23e0de9bb6e5f83eda4c7b2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1c3c2c9db23e0de9bb6e5f83eda4c7b2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1c3c2c9db23e0de9bb6e5f83eda4c7b2::$classMap;

        }, null, ClassLoader::class);
    }
}
